version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on `date`
      - echo Installing dependencies...
      - npm ci
      - echo Retrieving environment variables from Parameter Store...
      - export VITE_SOCIAL_AUTH_URL=$(aws ssm get-parameter --name "/harudew/VITE_SOCIAL_AUTH_URL" --query "Parameter.Value" --output text)
      - export VITE_GOOGLE_MAPS_API_KEY=$(aws ssm get-parameter --name "/harudew/VITE_GOOGLE_MAPS_API_KEY" --with-decryption --query "Parameter.Value" --output text)
      - export VITE_REDIRECT_URI=$(aws ssm get-parameter --name "/harudew/VITE_REDIRECT_URI" --query "Parameter.Value" --output text)
      - export VITE_VAPID_PUBLIC_KEY=$(aws ssm get-parameter --name "/harudew/VITE_VAPID_PUBLIC_KEY" --query "Parameter.Value" --output text)
      - export REACT_APP_API_BASE_URL=$(aws ssm get-parameter --name "/harudew/REACT_APP_API_BASE_URL" --query "Parameter.Value" --output text)
      - echo Environment variables loaded successfully
      - echo "=== Environment Variables Debug ==="
      - echo "VITE_SOCIAL_AUTH_URL = $VITE_SOCIAL_AUTH_URL"
      - echo "VITE_GOOGLE_MAPS_API_KEY = [HIDDEN]"
      - echo "VITE_REDIRECT_URI = $VITE_REDIRECT_URI"
      - echo "All VITE_ variables:"
      - printenv | grep VITE || echo "No VITE_ variables found"
      - echo "=== End Debug ==="
  build:
    commands:
      - echo Build started on `date`
      - echo Building the React application...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading to S3...
      - aws s3 sync dist/ s3://harudew.site --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id E264KENN1EBLKD --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist
